apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nidhogg-system
namePrefix: nidhogg-

resources:
  - ./resources.yaml
  - ./rbac.yaml
  - ./leader-election-rbac.yaml

#patches:
# Expose the prometheus metrics on default port
#  - target:
#      group: apps
#      version: v1
#      kind: StatefulSet
#    path: ./overlays/nidhogg-statefulset-prometheus-patch.yaml

images:
  - name: controller
    newName: ghcr.io/pelotech/nidhogg
    newTag: v0.5.3

replacements:
  - source:
      version: v1
      kind: Secret
      name: webhook-server-secret
      fieldPath: metadata.name
    targets:
      - select:
          group: apps
          version: v1
          kind: StatefulSet
          name: controller-manager
        fieldPaths:
          - spec.template.spec.containers.0.env.[name=SECRET_NAME].value
