name: publish-charts
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:
jobs:
  publish-charts:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Build dependencies Helm - nidhogg
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm dependency build charts/nidhogg
      - name: Chart | Push - nidhogg
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: nidhogg
          repository: pelotech/charts
          tag: ${{ github.ref_name }}
          app_version: ${{ github.ref_name }}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.github_token }}
